[WIP] Make table of contents for specified depth
suttacentral/publications pull request #52
Opened 2022-03-15 03:30 UTC by janwadolowski

#### Task: #[33](https://github.com/suttacentral/publications/issues/33)

#### When merged, this PR will:
- Change implementation of the method generating table of contents for epub based on HTML headings allowing for customising depth of headings (subsections of the ToC): 1-6
- Add some minor changes created alongside: updated README, some formatting changes, 1 tweak in mypy configuration

2022-03-15 03:33 UTC, janwadolowski commented
Function implemented but still requires testing.

2022-03-16 00:08 UTC, janwadolowski commented
Seems like I hit a rock with this. Achieved result is as depicted below (ToC presented in an online epub viewer):
![image](https://user-images.githubusercontent.com/23621477/158491458-45307d5f-2968-407d-a4a6-0dba1a3d19c7.png)

As you can see I achieved ToC generation based on headers structure and managed to get some nesting. Unfortunately right now the implementation doesn't handle such scenarios:
```yaml
- 1 (h1)
- 2 (h1)
-- 2.1 (h2)
-- 2.2 (h2)     <- this should be displayed as subsenction of `- 2 (h1)` but will be displayed as if it was `- 3 (h1)`
-- 2.3 (h2) 
-- 2.4 (h2) 
-- 2.4.1 (h3) 
-- 2.5 (h2)      <- same issue here (will be displayed as h1)
```

2022-03-16 10:56 UTC, sskoczyl requested changes

2022-03-16 11:12 UTC, janwadolowski commented on README.md
> +Install pre-commit got hooks:
Thanks for catching it

2022-03-16 11:13 UTC, merged